# Generated by Django 4.2.7 on 2026-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Общая стоимость'),
        ),
    ]
